### ISSUE TITLE
What does kafka in kafka_log mean ?

### ISSUE THREAD

**Issue by GaryCarneiro** [kaltura/nginx-kafka-log-module#11]
I see the example 
``kafka_log kafka:topic body message_id``

I understand topic means Kafka topic. But what does string `kafka:` mean ?

**Comment by erankor** [comment]
The module supports file output as well - `kafka_log file:/path/to/file body`.
This feature came from the module that was used as the basis for this one. Personally, I don't see any value in file output - you can just use nginx's builtin `access_log` directive for this.

**Comment by GaryCarneiro** [comment]
@erankor My question is kafka a short hostname ? 
Can I write it as `kafka_log kafka.server.example.com:kafka_topic_name body message_id` ?

**Comment by erankor** [comment]
no, it's a prefix to differentiate between file & kafka - it must be "kafka:" (like the http:// prefix of urls)

**Comment by GaryCarneiro** [comment]
Got it. its URI.
